name: maktrogps
description: A new Flutter project.

version: 1.1.0+70

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  backdrop: 0.7.1
  badges: 2.0.2
  battery_plus: 2.0.2
#  charts_flutter: 0.12.0
  cached_network_image: ^3.3.1
  #cached_network_image: 3.2.0
  carousel_slider: 4.0.0
  http: ^0.13.5
#  http: 1.2.1
  dio: ^4.0.6
  flutter_local_notifications: 9.2.0
  #flutter_local_notifications: 13.0.0
  #flutter_local_notifications: ^16.1.0
  fluttertoast: ^8.0.9
  universal_io: ^2.0.4
  #intl: 0.17.0
  intl: ^0.18.1
  shared_preferences: 2.0.11
  shimmer: 2.0.0
  cookie_jar: ^3.0.1
  flutter_easyloading: ^3.0.5
  google_maps_flutter: 2.1.1

  geolocator: ^7.0.3
  url_launcher: ^6.0.6
  scrollable_positioned_list: ^0.3.5
  animated_text_kit: ^4.2.2
  blinking_text: ^1.0.2
  settings_ui: ^2.0.2
  #fab_circular_menu: 1.0.2
  location: ^4.4.0
  dropdown_search: ^5.0.6
  firebase_core: 2.1.1
  #  firebase_auth: 4.1.0
  #firebase_storage: 11.0.3
  firebase_messaging: 14.0.3
  #  cloud_firestore: 4.0.3
  syncfusion_flutter_pdfviewer: ^20.3.57
  jiffy: ^5.0.0
  floating_bottom_navigation_bar: ^1.5.2
#  flutter_animarker: ^3.2.0
  flutter_animarker: ^3.1.1+2-alpha
  latlong2: ^0.8.0
  flutter_map: ^3.0.0
  font_awesome_flutter: ^10.3.0
#  flutter_launcher_icons: ^0.11.0
  audioplayers: ^0.20.1
  curved_navigation_bar: ^1.0.3
  flutter_inappwebview: ^5.7.2+3
  whatsapp_unilink: ^2.1.0
  bloc: ^8.1.1
  flutter_bloc: ^8.1.2
  equatable: ^2.0.5
  alxgration_speedometer: ^0.0.2

  syncfusion_flutter_gauges: ^20.3.56
  maps_toolkit: ^2.0.1
  odometer: ^3.0.0
  lottie: ^2.3.2
  syncfusion_flutter_charts: ^20.1.47
  provider: ^6.0.5
  text_to_speech: ^0.2.3
  permission_handler: ^11.0.0
  share_plus: ^4.5.3
  path_provider: ^2.0.13
  whatsapp_share: ^2.0.2
  #horizontal_calendar: ^1.0.0
  calendar_timeline: ^1.1.2

  bottom_navy_bar: any
  get: ^4.6.5
  video_player: ^2.7.0
  geocoding: ^2.2.0
  maps_launcher: ^2.2.1
  webview_flutter: ^4.7.0
  auto_size_text: ^3.0.0

  flutter_google_street_view: ^3.1.4
  flutter_file_downloader: ^1.1.2
 # flutter_polyline_points: ^2.1.0
 # flutter_polyline_points: ^2.0.0
  flutter_polyline_points: ^1.0.0
  custom_radio_grouped_button: ^2.2.1
  #easy_date_timeline: ^1.1.3
  #easy_date_timeline: ^1.0.4
  easy_date_timeline: ^1.0.0


  #awesome_notifications: any
  #sliding_up_panel2: ^3.3.0+1

#  flutter_datetime_picker: ^1.5.1
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1
  change_app_package_name: ^1.4.0


flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/appLogoNew.png"
  min_sdk_android: 21


flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:

    - assets/
    - assets/images/
    - assets/nepalicon/
    - assets/sensorsicon/
    - assets/nearbyplaceicon/
    - assets/appsicon/
    - assets/trackit/
    - assets/settingicon/
    - assets/speedoicon/
    - assets/rotatingicon/
    - assets/saftyappicon/
    - assets/tbtrack/
    - assets/icon/
    - assets/images/app_icon.png
    - assets/images/direction.png
    - assets/audio/
    - assets/images/engine.png
    - assets/images/locationpin.png
    - assets/images/listscreencar.png
    - assets/images/share.png
    - assets/images/route.png
    - assets/images/marker.png
    - assets/images/wifi.png
    - assets/images/dots.png
    - assets/speedoicon/servericon.png
    - assets/speedoicon/supporticon.png
    - assets/images/locationpinicon.png
    - assets/images/redcircle.png
    - assets/images/chargingicon.png
    - assets/tbtrack/sattelite.png

  fonts:
    - family: digital_font
      fonts:
        - asset: assets/fonts/assets_fonts_digital7.ttf
